In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/rockyt07/uber-sql-database/rideshare.db
/kaggle/input/datasets/rockyt07/uber-sql-database/schema.sql

In [7]:
import pandas as pd
import sqlite3
import os

# Try this path instead
for file in os.listdir("/kaggle/input"):
    print(file)

datasets

In [8]:
for file in os.listdir("/kaggle/input/datasets"):
    print(file)

rockyt07

In [9]:
for file in os.listdir("/kaggle/input/datasets/rockyt07"):
    print(file)

uber-sql-database

In [10]:
for file in os.listdir("/kaggle/input/datasets/rockyt07/uber-sql-database"):
    print(file)

rideshare.db
schema.sql

In [11]:
import sqlite3
import pandas as pd

# Connect directly to the database
conn = sqlite3.connect("/kaggle/input/datasets/rockyt07/uber-sql-database/rideshare.db")

# See all the tables inside it
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", conn)
print(tables)

            name
0          users
1        drivers
2         riders
3      locations
4          trips
5       payments
6        reviews
7  cancellations

In [12]:
# Preview each table
for table in ["users", "drivers", "riders", "locations", "trips", "payments", "reviews", "cancellations"]:
    print(f"\n--- {table.upper()} ---")
    df = pd.read_sql(f"SELECT * FROM {table} LIMIT 5", conn)
    print(df)

--- USERS ---
   user_id              name                        email            phone  \
0        1       David White        david.white@gmail.com  +1-809-169-4853
1        2      Justin Young      justin.young@icloud.com  +1-808-140-2343
2        3       Scott Kelly       scott.kelly@icloud.com  +1-523-367-4346
3        4  Dorothy Phillips   dorothy.phillips@yahoo.com  +1-887-760-5915
4        5   Barbara Johnson  barbara.johnson@hotmail.com  +1-836-676-2638

          city date_joined  is_driver
0      Houston  2019-09-03          0
1      Houston  2022-09-08          1
2  Los Angeles  2020-05-03          0
3      Houston  2020-10-09          0
4     New York  2022-01-06          1

--- DRIVERS ---
   driver_id  user_id vehicle_make vehicle_model  vehicle_year license_plate  \
0          1     1781          Kia          Soul          2015      ZVJ-2140
1          2      408      Hyundai        Tucson          2016      WLW-3906
2          3      693      Hyundai        Sonata          2014      WEA-5140
3          4      187       Nissan         Rogue          2021      KDE-9978
4          5     1499         Ford        Fusion          2019      EKJ-8600

   rating   join_date  is_active
0    4.10  2019-12-22          1
1    4.21  2020-12-14          1
2    3.81  2023-07-25          1
3    4.82  2020-01-11          1
4    3.30  2023-07-15          0

--- RIDERS ---
   rider_id  user_id  rating  total_trips           created_at
0         1     1958    4.66            1  2020-09-13 01:52:12
1         2      373    3.76            2  2019-11-03 13:23:24
2         3      680    3.03            8  2020-01-23 08:54:39
3         4     1190    3.31            1  2019-11-06 23:53:19
4         5     1970    3.71           36  2023-09-17 01:02:59

--- LOCATIONS ---
   location_id          zone_name      city  latitude  longitude    zone_type
0            1       Times Square  New York   40.7580   -73.9855   commercial
1            2        JFK Airport  New York   40.6413   -73.7781      airport
2            3  LaGuardia Airport  New York   40.7769   -73.8740      airport
3            4   Brooklyn Heights  New York   40.6960   -73.9946  residential
4            5             Harlem  New York   40.8116   -73.9465  residential

--- TRIPS ---
   trip_id  rider_id  driver_id  pickup_location_id  dropoff_location_id  \
0        1         1         34                  26                   29
1        2         2        185                  18                   12
2        3         2        126                  13                   15
3        4         2        255                  10                    6
4        5         3        186                  37                   31

          requested_at           started_at         completed_at     status  \
0  2024-06-24 12:20:11  2024-06-24 12:29:11  2024-06-24 14:24:11  completed
1  2024-01-25 20:52:28  2024-01-25 20:54:28                 None  cancelled
2  2023-08-17 09:30:06  2023-08-17 09:32:06  2023-08-17 09:36:06  completed
3  2022-11-21 09:53:31  2022-11-21 09:58:31  2022-11-21 10:17:31  completed
4  2022-01-15 14:04:56  2022-01-15 14:12:56  2022-01-15 14:56:56  completed

   distance_km  duration_mins  base_fare  surge_multiplier  total_fare  \
0        39.14            115      68.55               1.0       68.55
1         9.53             22      17.38               1.0       17.38
2         2.78              4       6.36               1.0        6.36
3        14.25             19      21.98               1.0       21.98
4        41.54             44      56.99               1.0       56.99

  payment_method
0         wallet
1         wallet
2         wallet
3           cash
4         wallet

--- PAYMENTS ---
   payment_id  trip_id  amount  method   status              paid_at
0           1        1   68.55  wallet  success  2024-06-24 14:24:15
1           2        3    6.36  wallet  success  2023-08-17 09:36:16
2           3        4   21.98    cash  success  2022-11-21 10:17:36
3           4        5   56.99  wallet  success  2022-01-15 14:57:02
4           5        6   55.56    cash  success  2022-05-05 08:34:02

--- REVIEWS ---
   review_id  trip_id  reviewer_id  reviewee_id  rating  \
0          1        1         1958         1001       4
1          2        1         1001         1958       4
2          3        3          324          373       4
3          4        4          373            5       4
4          5        5          680         1356       3

                       comment          reviewed_at
0       Very comfortable ride.  2024-06-24 14:52:11
1  Super friendly and helpful.  2024-06-24 16:09:11
2              Very clean car.  2023-08-17 11:08:06
3                         None  2022-11-21 11:30:31
4                         None  2022-01-15 15:25:56

--- CANCELLATIONS ---
   cancel_id  trip_id cancelled_by                reason         cancelled_at
0          1        2       driver    personal emergency  2024-01-25 20:55:28
1          2        7       driver          wrong pickup  2023-06-02 19:32:48
2          3       16       driver  rider rating too low  2022-05-13 15:56:17
3          4       29       driver  rider rating too low  2022-03-06 04:48:56
4          5       63        rider    personal emergency  2022-07-14 23:33:56

In [13]:
for table in ["users", "drivers", "riders", "locations", "trips", "payments", "reviews", "cancellations"]:
    print(f"\n--- {table.upper()} ---")
    df = pd.read_sql(f"SELECT * FROM {table} LIMIT 1", conn)
    print(df.columns.tolist())

--- USERS ---
['user_id', 'name', 'email', 'phone', 'city', 'date_joined', 'is_driver']

--- DRIVERS ---
['driver_id', 'user_id', 'vehicle_make', 'vehicle_model', 'vehicle_year', 'license_plate', 'rating', 'join_date', 'is_active']

--- RIDERS ---
['rider_id', 'user_id', 'rating', 'total_trips', 'created_at']

--- LOCATIONS ---
['location_id', 'zone_name', 'city', 'latitude', 'longitude', 'zone_type']

--- TRIPS ---
['trip_id', 'rider_id', 'driver_id', 'pickup_location_id', 'dropoff_location_id', 'requested_at', 'started_at', 'completed_at', 'status', 'distance_km', 'duration_mins', 'base_fare', 'surge_multiplier', 'total_fare', 'payment_method']

--- PAYMENTS ---
['payment_id', 'trip_id', 'amount', 'method', 'status', 'paid_at']

--- REVIEWS ---
['review_id', 'trip_id', 'reviewer_id', 'reviewee_id', 'rating', 'comment', 'reviewed_at']

--- CANCELLATIONS ---
['cancel_id', 'trip_id', 'cancelled_by', 'reason', 'cancelled_at']

In [14]:
query = """
SELECT city, COUNT(*) as total_users
FROM users
GROUP BY city
ORDER BY total_users DESC
"""

pd.read_sql(query, conn)

          city  total_users
0      Houston          552
1  Los Angeles          497
2     New York          480
3      Chicago          471

In [15]:
query = """
SELECT u.name, d.rating, d.vehicle_make, d.vehicle_model, d.vehicle_year
FROM drivers d
JOIN users u ON d.user_id = u.user_id
ORDER BY d.rating DESC
LIMIT 5
"""

pd.read_sql(query, conn)

              name  rating vehicle_make vehicle_model  vehicle_year
0     Cynthia Cook    5.00    Chevrolet     Silverado          2022
1  Patricia Bailey    5.00        Mazda          MX-5          2013
2    Brandon Reyes    4.99        Honda          CR-V          2014
3   Gregory Morris    4.99         Ford        Escape          2017
4    Donna Morales    4.99        Tesla       Model X          2015

In [16]:
query = """
SELECT 
    ROUND(AVG(total_fare), 2) as avg_fare,
    ROUND(MIN(total_fare), 2) as cheapest_trip,
    ROUND(MAX(total_fare), 2) as most_expensive_trip
FROM trips
"""

pd.read_sql(query, conn)

   avg_fare  cheapest_trip  most_expensive_trip
0     36.01           3.65               224.27

In [17]:
query = """
SELECT reason, COUNT(*) as total_cancellations
FROM cancellations
GROUP BY reason
ORDER BY total_cancellations DESC
"""

pd.read_sql(query, conn)

                  reason  total_cancellations
0     personal emergency                  396
1          too long wait                  284
2        changed my mind                  283
3        waited too long                  262
4         price too high                  250
5      duplicate booking                  249
6     found another ride                  248
7         driver too far                  231
8           wrong pickup                  137
9           system error                  133
10         area not safe                  133
11         vehicle issue                  128
12  rider rating too low                  124
13    rider unresponsive                  108

In [18]:
query = """
SELECT method, COUNT(*) as total_payments,
    ROUND(SUM(amount), 2) as total_revenue
FROM payments
GROUP BY method
ORDER BY total_payments DESC
"""

pd.read_sql(query, conn)

   method  total_payments  total_revenue
0    card            5700      208034.67
1  wallet            5621      200500.16
2    cash            5506      196055.09